/**
 * Calm Quest — affirmations (Phase 6 in-house content pack).
 *
 * 75 affirmations: 15 per theme × 5. Each is ≤1 sentence, gentle, faith-rooted
 * but non-denominational. No toxic positivity, no guaranteed outcomes, no
 * medical claims, no denominational markers. Replaces the Phase 1 SAMPLE
 * bundle wholesale (see CONTENT_META in index.ts).
 */
import type { Affirmation } from '../models/types';

export const affirmations: Affirmation[] = [
  { id: "aff-gratitude-01", theme: "gratitude", text: "Some good came to me today — I can look for it and probably find it." },
  { id: "aff-gratitude-02", theme: "gratitude", text: "I am learning to notice small gifts in ordinary hours." },
  { id: "aff-gratitude-03", theme: "gratitude", text: "Thankfulness is a practice, not a mood I have to wait for." },
  { id: "aff-gratitude-04", theme: "gratitude", text: "There is enough in this moment to be glad about." },
  { id: "aff-gratitude-05", theme: "gratitude", text: "I can hold thanks and hard feelings in the same hand." },
  { id: "aff-gratitude-06", theme: "gratitude", text: "Every day hides at least one small good — I can look gently for it." },
  { id: "aff-gratitude-07", theme: "gratitude", text: "Gratitude grows in me a little at a time." },
  { id: "aff-gratitude-08", theme: "gratitude", text: "I am allowed to enjoy good things simply because they are good." },
  { id: "aff-gratitude-09", theme: "gratitude", text: "What I notice, I treasure; what I treasure, I keep." },
  { id: "aff-gratitude-10", theme: "gratitude", text: "Even on a heavy day, something light is still offered." },
  { id: "aff-gratitude-11", theme: "gratitude", text: "I can give thanks without pretending everything is fine." },
  { id: "aff-gratitude-12", theme: "gratitude", text: "My heart is making room for what is already given." },
  { id: "aff-gratitude-13", theme: "gratitude", text: "Small joys count as joys." },
  { id: "aff-gratitude-14", theme: "gratitude", text: "I am practicing the art of receiving — no earning required." },
  { id: "aff-gratitude-15", theme: "gratitude", text: "The gift of today is worth one moment of honest thanks." },
  { id: "aff-stillness-01", theme: "stillness", text: "I am allowed to slow down; nothing urgent waits for me there." },
  { id: "aff-stillness-02", theme: "stillness", text: "Stillness is a place I can return to, not a thing I have to earn." },
  { id: "aff-stillness-03", theme: "stillness", text: "My breathing is enough of a task for this minute." },
  { id: "aff-stillness-04", theme: "stillness", text: "I do not have to answer every noise; some can simply pass." },
  { id: "aff-stillness-05", theme: "stillness", text: "Rest is an invitation, and I can accept it." },
  { id: "aff-stillness-06", theme: "stillness", text: "Quiet is not emptiness; it is room to breathe." },
  { id: "aff-stillness-07", theme: "stillness", text: "I can set the load down for a moment — it will still be there if I return." },
  { id: "aff-stillness-08", theme: "stillness", text: "The peace I seek is closer than the hurry suggests." },
  { id: "aff-stillness-09", theme: "stillness", text: "Pausing is part of moving well." },
  { id: "aff-stillness-10", theme: "stillness", text: "My shoulders can be softer than they have been carrying." },
  { id: "aff-stillness-11", theme: "stillness", text: "There is time enough for the things that matter." },
  { id: "aff-stillness-12", theme: "stillness", text: "I can be still without needing to be productive." },
  { id: "aff-stillness-13", theme: "stillness", text: "Silence is a friend I am learning to trust." },
  { id: "aff-stillness-14", theme: "stillness", text: "One unhurried minute is already a gift to myself." },
  { id: "aff-stillness-15", theme: "stillness", text: "I carry my own pace; I do not chase someone else's." },
  { id: "aff-purpose-01", theme: "purpose", text: "My day can hold meaning without being impressive." },
  { id: "aff-purpose-02", theme: "purpose", text: "I am free to choose one small direction and walk it gently." },
  { id: "aff-purpose-03", theme: "purpose", text: "Purpose is found in faithful small steps, not grand arrivals." },
  { id: "aff-purpose-04", theme: "purpose", text: "The work of today can be done with a whole heart." },
  { id: "aff-purpose-05", theme: "purpose", text: "I do not need to know the whole path to take one good step." },
  { id: "aff-purpose-06", theme: "purpose", text: "My gifts are enough to begin with, exactly as they are." },
  { id: "aff-purpose-07", theme: "purpose", text: "I can serve the people right in front of me." },
  { id: "aff-purpose-08", theme: "purpose", text: "What I do with love is never wasted." },
  { id: "aff-purpose-09", theme: "purpose", text: "I am allowed to be a beginner at something new." },
  { id: "aff-purpose-10", theme: "purpose", text: "Each day opens with room for one intention." },
  { id: "aff-purpose-11", theme: "purpose", text: "My ordinary work can be a form of care." },
  { id: "aff-purpose-12", theme: "purpose", text: "I am free to try, and free to learn." },
  { id: "aff-purpose-13", theme: "purpose", text: "The good I do today may be small — and still be good." },
  { id: "aff-purpose-14", theme: "purpose", text: "I can walk toward hope without needing proof it will arrive." },
  { id: "aff-purpose-15", theme: "purpose", text: "My life is a story still being written, and today is a page." },
  { id: "aff-forgiveness-01", theme: "forgiveness", text: "I can release today what I do not need to carry." },
  { id: "aff-forgiveness-02", theme: "forgiveness", text: "Forgiveness is a choice I can make in small steps." },
  { id: "aff-forgiveness-03", theme: "forgiveness", text: "I am not required to feel warm to begin letting go." },
  { id: "aff-forgiveness-04", theme: "forgiveness", text: "There is a gentleness in me that can be offered even now." },
  { id: "aff-forgiveness-05", theme: "forgiveness", text: "What others meant as harm does not have to define my day." },
  { id: "aff-forgiveness-06", theme: "forgiveness", text: "I can set down the old words and keep walking." },
  { id: "aff-forgiveness-07", theme: "forgiveness", text: "Grace begins with me — offered to myself too." },
  { id: "aff-forgiveness-08", theme: "forgiveness", text: "Forgiveness is freedom, even when it is quiet." },
  { id: "aff-forgiveness-09", theme: "forgiveness", text: "I can hand the heaviest feelings over, one at a time." },
  { id: "aff-forgiveness-10", theme: "forgiveness", text: "Letting go is not forgetting; it is choosing to carry less." },
  { id: "aff-forgiveness-11", theme: "forgiveness", text: "I am allowed to forgive at the pace I can honestly manage." },
  { id: "aff-forgiveness-12", theme: "forgiveness", text: "Mercy toward myself today is not weakness; it is wisdom." },
  { id: "aff-forgiveness-13", theme: "forgiveness", text: "The story is not over, and I can write today's line." },
  { id: "aff-forgiveness-14", theme: "forgiveness", text: "I can be patient with my own unfolding." },
  { id: "aff-forgiveness-15", theme: "forgiveness", text: "There is room in my heart for both hurt and hope." },
  { id: "aff-patience-01", theme: "patience", text: "Growth happens on its own schedule, and that is alright." },
  { id: "aff-patience-02", theme: "patience", text: "I can meet today's pace without hurrying it." },
  { id: "aff-patience-03", theme: "patience", text: "Waiting is part of the work, and I am working." },
  { id: "aff-patience-04", theme: "patience", text: "I am learning to be gentle with the in-between." },
  { id: "aff-patience-05", theme: "patience", text: "What is still forming in me deserves time." },
  { id: "aff-patience-06", theme: "patience", text: "Patience is a quiet strength, not a lack of progress." },
  { id: "aff-patience-07", theme: "patience", text: "I can move slowly and still move forward." },
  { id: "aff-patience-08", theme: "patience", text: "The best things often take the most time." },
  { id: "aff-patience-09", theme: "patience", text: "I am not behind; I am simply where I am." },
  { id: "aff-patience-10", theme: "patience", text: "My calm can remain even when the pace around me quickens." },
  { id: "aff-patience-11", theme: "patience", text: "One slow breath is enough for this moment." },
  { id: "aff-patience-12", theme: "patience", text: "I can trust the process without seeing the whole picture." },
  { id: "aff-patience-13", theme: "patience", text: "Being patient with myself is how I learn patience at all." },
  { id: "aff-patience-14", theme: "patience", text: "There is no rush to become what I am already becoming." },
  { id: "aff-patience-15", theme: "patience", text: "I will be as kind to my own timeline as I am to a friend's." },
];
