/**
 * Calm Quest — daily quests (Phase 6 in-house content pack).
 *
 * 60 quests: 5 themes × 12; per theme 3 read_reflect (verseId + reflection +
 * 3 checkInOptions), 3 act (actionPrompt), 3 pause (durationSeconds 60 +
 * pausePrompt), 3 write (journalPrompt). Faith-aligned, non-denominational;
 * grace-toned; no medical claims; no streak-guilt; no guaranteed outcomes
 * ("invites", not "will fix"). Titles ≤ 6 words.
 *
 * Read & Reflect quests carry a `verseId` into src/content/verses.ts (WEB,
 * public domain). This bundle replaces the Phase 1 SAMPLE set wholesale
 * (see CONTENT_META in index.ts).
 */
import type { Quest } from '../models/types';

export const quests: Quest[] = [

  // =========================================================================== gratitude
  {
    id: "q-gratitude-01",
    theme: "gratitude",
    type: "read_reflect",
    title: "A kindness worth naming",
    verseId: "verse-psalm-107-1",
    reflection: "The day has held something good, even if you had to look twice to see it. Naming it is enough.",
    checkInOptions: [{ label: "Peace" }, { label: "Grateful" }, { label: "Calm" }],
  },
  {
    id: "q-gratitude-02",
    theme: "gratitude",
    type: "read_reflect",
    title: "Thanks wherever you are",
    verseId: "verse-ephes-5-20",
    reflection: "Gratitude is not pretending pain away. It is letting thanks sit beside whatever else is true — both can be real.",
    checkInOptions: [{ label: "Peace" }, { label: "Courage" }, { label: "Rest" }],
  },
  {
    id: "q-gratitude-03",
    theme: "gratitude",
    type: "read_reflect",
    title: "Coming with open hands",
    verseId: "verse-psalm-95-2",
    reflection: "Before you ask for anything, there is already something offered. You can arrive empty-handed.",
    checkInOptions: [{ label: "Calm" }, { label: "Trust" }, { label: "Hope" }],
  },
  {
    id: "q-gratitude-04",
    theme: "gratitude",
    type: "act",
    title: "One small kindness noticed",
    actionPrompt: "Watch for one moment of kindness today — someone's patience, a door held, a word that helped. When you see it, let it land instead of rushing past.",
  },
  {
    id: "q-gratitude-05",
    theme: "gratitude",
    type: "act",
    title: "A quiet list of three",
    actionPrompt: "At some point today, quietly count three things you are glad to have — they can be as plain as water, warmth, or a familiar voice. No writing required.",
  },
  {
    id: "q-gratitude-06",
    theme: "gratitude",
    type: "act",
    title: "Say it out loud once",
    actionPrompt: "Once today, say one thing you are thankful for — out loud, even if it is just to yourself or to the room. Hearing it changes how it lands.",
  },
  {
    id: "q-gratitude-07",
    theme: "gratitude",
    type: "pause",
    title: "A breath that says thank you",
    durationSeconds: 60,
    pausePrompt: "For one minute, let each breath be a small thank-you — no words needed, just the rhythm of it.",
  },
  {
    id: "q-gratitude-08",
    theme: "gratitude",
    type: "pause",
    title: "Savor one small thing",
    durationSeconds: 60,
    pausePrompt: "Choose something simple — a drink, a view, a warmth — and give it sixty unhurried seconds of your full attention.",
  },
  {
    id: "q-gratitude-09",
    theme: "gratitude",
    type: "pause",
    title: "Stillness with open eyes",
    durationSeconds: 60,
    pausePrompt: "Sit quietly for one minute with your eyes open. Let whatever is already good in this room become visible.",
  },
  {
    id: "q-gratitude-10",
    theme: "gratitude",
    type: "write",
    title: "Today's quiet gift",
    journalPrompt: "Write one line about one good thing that came to you today — however small it seems.",
  },
  {
    id: "q-gratitude-11",
    theme: "gratitude",
    type: "write",
    title: "Gratitude without conditions",
    journalPrompt: "Write one line of thanks that asks for nothing in return.",
  },
  {
    id: "q-gratitude-12",
    theme: "gratitude",
    type: "write",
    title: "What you would keep",
    journalPrompt: "If today had one moment worth keeping, what would it be? One line is plenty.",
  },

  // =========================================================================== stillness
  {
    id: "q-stillness-01",
    theme: "stillness",
    type: "read_reflect",
    title: "A quieted soul",
    verseId: "verse-psalm-131-2",
    reflection: "Stillness can feel like surrender — and sometimes it is exactly the letting-go that lets you rest.",
    checkInOptions: [{ label: "Peace" }, { label: "Rest" }, { label: "Calm" }],
  },
  {
    id: "q-stillness-02",
    theme: "stillness",
    type: "read_reflect",
    title: "Waiting in silence",
    verseId: "verse-psalm-62-5",
    reflection: "Silence is not empty. It is a place to stand while the noise settles around you.",
    checkInOptions: [{ label: "Peace" }, { label: "Trust" }, { label: "Calm" }],
  },
  {
    id: "q-stillness-03",
    theme: "stillness",
    type: "read_reflect",
    title: "Rest is an invitation",
    verseId: "verse-mark-6-31",
    reflection: "Even the ones who were needed most were invited away to rest. You do not have to earn a pause.",
    checkInOptions: [{ label: "Rest" }, { label: "Peace" }, { label: "Gentle" }],
  },
  {
    id: "q-stillness-04",
    theme: "stillness",
    type: "act",
    title: "One thing done slowly",
    actionPrompt: "Pick one small task today — a drink, a walk, a doorway — and do it noticeably slower than usual. Let it take the time it takes.",
  },
  {
    id: "q-stillness-05",
    theme: "stillness",
    type: "act",
    title: "A five-minute screen break",
    actionPrompt: "For five minutes today, put the phone face-down in another room. Nothing urgent will be missed.",
  },
  {
    id: "q-stillness-06",
    theme: "stillness",
    type: "act",
    title: "Make a small quiet corner",
    actionPrompt: "Find or make one small quiet spot today — a chair by the window, a cushion, a bench — and spend two minutes there.",
  },
  {
    id: "q-stillness-07",
    theme: "stillness",
    type: "pause",
    title: "One unhurried minute",
    durationSeconds: 60,
    pausePrompt: "One minute of nothing-to-do. Let your shoulders drop, your hands rest, and the clock do the work.",
  },
  {
    id: "q-stillness-08",
    theme: "stillness",
    type: "pause",
    title: "Listening to the room",
    durationSeconds: 60,
    pausePrompt: "For sixty seconds, listen without fixing anything — the hum, the wind, the quiet. Just let it be.",
  },
  {
    id: "q-stillness-09",
    theme: "stillness",
    type: "pause",
    title: "Three slow breaths",
    durationSeconds: 60,
    pausePrompt: "Take three breaths, each slower than the last. You do not have to count them perfectly — just feel the space between.",
  },
  {
    id: "q-stillness-10",
    theme: "stillness",
    type: "write",
    title: "What quiet feels like",
    journalPrompt: "In one line, describe what stillness felt like today — or what you imagine it might.",
  },
  {
    id: "q-stillness-11",
    theme: "stillness",
    type: "write",
    title: "What you set down",
    journalPrompt: "Write one thing you set down today, even for a minute — a worry, a task, a should.",
  },
  {
    id: "q-stillness-12",
    theme: "stillness",
    type: "write",
    title: "A word for the noise",
    journalPrompt: "If today's noise had a shape, what would it be? One honest line is enough.",
  },

  // =========================================================================== purpose
  {
    id: "q-purpose-01",
    theme: "purpose",
    type: "read_reflect",
    title: "A plan of peace",
    verseId: "verse-jer-29-11",
    reflection: "You do not have to have the whole future figured out. One hopeful next step is enough for today.",
    checkInOptions: [{ label: "Hope" }, { label: "Peace" }, { label: "Calm" }],
  },
  {
    id: "q-purpose-02",
    theme: "purpose",
    type: "read_reflect",
    title: "The good that is required",
    verseId: "verse-micah-6-8",
    reflection: "Purpose does not have to be grand. Acting justly, loving mercy, walking humbly — these fit inside an ordinary day.",
    checkInOptions: [{ label: "Steady" }, { label: "Peace" }, { label: "Gentle" }],
  },
  {
    id: "q-purpose-03",
    theme: "purpose",
    type: "read_reflect",
    title: "Work done with the heart",
    verseId: "verse-col-3-23",
    reflection: "Whatever your hands find to do today can be done fully — not for applause, but because it is yours to do.",
    checkInOptions: [{ label: "Steady" }, { label: "Courage" }, { label: "Calm" }],
  },
  {
    id: "q-purpose-04",
    theme: "purpose",
    type: "act",
    title: "One task, all the way",
    actionPrompt: "Choose one small task today and finish it gently — completely, but without hurry. Completion is its own quiet reward.",
  },
  {
    id: "q-purpose-05",
    theme: "purpose",
    type: "act",
    title: "Use a gift you have",
    actionPrompt: "Use one of your gifts today, however small — a listening ear, a practical hand, a word of encouragement. You do not need to announce it.",
  },
  {
    id: "q-purpose-06",
    theme: "purpose",
    type: "act",
    title: "A tiny step toward a wish",
    actionPrompt: "Think of one thing you hope for. Take one step toward it that fits comfortably in today — even a five-minute one.",
  },
  {
    id: "q-purpose-07",
    theme: "purpose",
    type: "pause",
    title: "Where am I headed",
    durationSeconds: 60,
    pausePrompt: "One minute to sit with the question: what small direction feels right for this day? No answering required.",
  },
  {
    id: "q-purpose-08",
    theme: "purpose",
    type: "pause",
    title: "The work of resting",
    durationSeconds: 60,
    pausePrompt: "Sometimes purpose is simply pausing so you can keep going well. Give today sixty seconds of that.",
  },
  {
    id: "q-purpose-09",
    theme: "purpose",
    type: "pause",
    title: "A moment of commitment",
    durationSeconds: 60,
    pausePrompt: "For one minute, hold in your mind the one thing you intend to give today — your attention, your time, your care.",
  },
  {
    id: "q-purpose-10",
    theme: "purpose",
    type: "write",
    title: "One good task today",
    journalPrompt: "Write one line about one meaningful thing you did today — even if only you noticed it.",
  },
  {
    id: "q-purpose-11",
    theme: "purpose",
    type: "write",
    title: "The why behind the what",
    journalPrompt: "In one line, name why one thing you did today matters to you.",
  },
  {
    id: "q-purpose-12",
    theme: "purpose",
    type: "write",
    title: "A seed of intention",
    journalPrompt: "Write one small intention for tomorrow — just one, gently worded, no pressure attached.",
  },

  // =========================================================================== forgiveness
  {
    id: "q-forgiveness-01",
    theme: "forgiveness",
    type: "read_reflect",
    title: "Forgiven as you forgive",
    verseId: "verse-matt-6-14",
    reflection: "Forgiveness is not a demand to feel warm. It is a choice to release — and it can be made in small, honest steps.",
    checkInOptions: [{ label: "Peace" }, { label: "Calm" }, { label: "Gentle" }],
  },
  {
    id: "q-forgiveness-02",
    theme: "forgiveness",
    type: "read_reflect",
    title: "As far as east from west",
    verseId: "verse-psalm-103-12",
    reflection: "However far your regrets feel, there is a story in which they are separated from you completely. You can rest in that.",
    checkInOptions: [{ label: "Peace" }, { label: "Trust" }, { label: "Rest" }],
  },
  {
    id: "q-forgiveness-03",
    theme: "forgiveness",
    type: "read_reflect",
    title: "A heart ready to forgive",
    verseId: "verse-psalm-86-5",
    reflection: "Readiness to forgive is a posture, not a performance. You can lean toward it a little at a time.",
    checkInOptions: [{ label: "Gentle" }, { label: "Peace" }, { label: "Hope" }],
  },
  {
    id: "q-forgiveness-04",
    theme: "forgiveness",
    type: "act",
    title: "A small release",
    actionPrompt: "Today, release one small grudge — an old snub, a tiny annoyance, a word you are still turning over. Let it be a little lighter.",
  },
  {
    id: "q-forgiveness-05",
    theme: "forgiveness",
    type: "act",
    title: "Extend patience to someone",
    actionPrompt: "Give one person more patience than you might normally offer today — a slow driver, a tired clerk, a friend who forgot. It is a quiet act of grace.",
  },
  {
    id: "q-forgiveness-06",
    theme: "forgiveness",
    type: "act",
    title: "A gentle word instead",
    actionPrompt: "When you feel the start of irritation today, offer one gentle word instead — to someone else or to yourself.",
  },
  {
    id: "q-forgiveness-07",
    theme: "forgiveness",
    type: "pause",
    title: "Letting the shoulders down",
    durationSeconds: 60,
    pausePrompt: "One minute to notice where you are holding something — a jaw, a shoulder, a fist — and to let it soften.",
  },
  {
    id: "q-forgiveness-08",
    theme: "forgiveness",
    type: "pause",
    title: "A breath for a hard memory",
    durationSeconds: 60,
    pausePrompt: "For one minute, breathe gently toward one memory you are still carrying. You are not trying to erase it — just to loosen its grip.",
  },
  {
    id: "q-forgiveness-09",
    theme: "forgiveness",
    type: "pause",
    title: "Extending grace inward",
    durationSeconds: 60,
    pausePrompt: "Sixty seconds of the same patience you would offer a friend — aimed at yourself, without conditions.",
  },
  {
    id: "q-forgiveness-10",
    theme: "forgiveness",
    type: "write",
    title: "What you are releasing",
    journalPrompt: "Write one line naming one thing you are letting go of today — even just a fraction of it.",
  },
  {
    id: "q-forgiveness-11",
    theme: "forgiveness",
    type: "write",
    title: "A letter you do not send",
    journalPrompt: "In one line, say what you would want forgiven — by someone else, or by yourself.",
  },
  {
    id: "q-forgiveness-12",
    theme: "forgiveness",
    type: "write",
    title: "Grace given and received",
    journalPrompt: "Write one line: one way you received grace today, or one way you gave it.",
  },

  // =========================================================================== patience
  {
    id: "q-patience-01",
    theme: "patience",
    type: "read_reflect",
    title: "A settled heart",
    verseId: "verse-james-5-8",
    reflection: "Patience is not waiting well by luck. It is a practiced stillness of the heart — and practice takes time, which is itself patient.",
    checkInOptions: [{ label: "Steady" }, { label: "Peace" }, { label: "Calm" }],
  },
  {
    id: "q-patience-02",
    theme: "patience",
    type: "read_reflect",
    title: "The patient in spirit",
    verseId: "verse-eccl-7-8",
    reflection: "What is finished is not always what is best. Being gentle in the waiting counts for more than being forceful in the hurry.",
    checkInOptions: [{ label: "Gentle" }, { label: "Steady" }, { label: "Peace" }],
  },
  {
    id: "q-patience-03",
    theme: "patience",
    type: "read_reflect",
    title: "Resting while you wait",
    verseId: "verse-psalm-37-7",
    reflection: "Waiting can be an act of trust, not a waste. You can rest in the in-between instead of pacing it.",
    checkInOptions: [{ label: "Rest" }, { label: "Trust" }, { label: "Peace" }],
  },
  {
    id: "q-patience-04",
    theme: "patience",
    type: "act",
    title: "One patient moment",
    actionPrompt: "Today, choose one moment to be deliberately patient — in a line, in traffic, in a conversation. Let it be its own small grace.",
  },
  {
    id: "q-patience-05",
    theme: "patience",
    type: "act",
    title: "Let something ripen",
    actionPrompt: "Pick something today you would normally rush — an email that could wait till tomorrow, a decision, a reply — and let it sit a little longer.",
  },
  {
    id: "q-patience-06",
    theme: "patience",
    type: "act",
    title: "Slow down one ritual",
    actionPrompt: "Take one ordinary ritual — making tea, brushing teeth, opening mail — and do it twice as slowly, without hurrying to the next thing.",
  },
  {
    id: "q-patience-07",
    theme: "patience",
    type: "pause",
    title: "Sitting with the in-between",
    durationSeconds: 60,
    pausePrompt: "One minute of simply being in the middle of things — nothing resolved, nothing forced.",
  },
  {
    id: "q-patience-08",
    theme: "patience",
    type: "pause",
    title: "The long, slow breath",
    durationSeconds: 60,
    pausePrompt: "For sixty seconds, breathe in slowly and let the out-breath be even slower. Patience has a rhythm — this is it.",
  },
  {
    id: "q-patience-09",
    theme: "patience",
    type: "pause",
    title: "Watching without fixing",
    durationSeconds: 60,
    pausePrompt: "Look at one thing — a plant, the sky, a cup — for a full minute without improving, changing, or finishing it.",
  },
  {
    id: "q-patience-10",
    theme: "patience",
    type: "write",
    title: "What is still growing",
    journalPrompt: "Write one line about something in your life that is still growing — and what it needs from you right now.",
  },
  {
    id: "q-patience-11",
    theme: "patience",
    type: "write",
    title: "A wait that taught you",
    journalPrompt: "In one line, remember a time when waiting turned out to be better than hurrying.",
  },
  {
    id: "q-patience-12",
    theme: "patience",
    type: "write",
    title: "Gentle with yourself",
    journalPrompt: "Write one line of patience you could offer yourself for something that is taking longer than you hoped.",
  },
];
